/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_knet_seal_financial_api_KnetFinancialHttpApi */

#ifndef _Included_cn_knet_seal_financial_api_KnetFinancialHttpApi
#define _Included_cn_knet_seal_financial_api_KnetFinancialHttpApi
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_knet_seal_financial_api_KnetFinancialHttpApi
 * Method:    ct
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_knet_seal_financial_api_KnetFinancialHttpApi_ct
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     cn_knet_seal_financial_api_KnetFinancialHttpApi
 * Method:    pt
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_knet_seal_financial_api_KnetFinancialHttpApi_pt
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     cn_knet_seal_financial_api_KnetFinancialHttpApi
 * Method:    cpt
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_knet_seal_financial_api_KnetFinancialHttpApi_cpt
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
